services:
  db:
    image: postgres:latest
    env_file: .docker-env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - barev
    restart: always

  ganache:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ganache
    stop_grace_period: 5s
    env_file: .docker-env
    volumes:
      - ganache:/data
    ports:
      - ${GANACHE_PORT}:${GANACHE_PORT}
    networks:
      - barev
    restart: always

  blockchain:
    depends_on:
      - ganache
    build:
      context: .
      dockerfile: ./docker/Dockerfile.blockchain
    stop_grace_period: 5s
    env_file: .docker-env
    ports:
      - ${BLOCKCHAIN_PORT}:${BLOCKCHAIN_PORT}
    networks:
      - barev
    restart: always

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.django
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"

  #   networks:
  #     - barev
  #   depends_on:
  #     - db
  #   env_file:
  #     - .docker-env
  #   restart: always

volumes:
  postgres:
  ganache:

networks:
  barev:
    driver: bridge
