version: '3'

services:
  db:
    image: postgres:latest
    env_file: .docker-env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

    # networks:
    #   - barev

    restart: always
  # ganache:
  #   stop_grace_period: 5s
  #   image: trufflesuite/ganache-cli:latest
  #   volumes:
  #     - ganache:/data
  #   ports:
  #     - 8545:8545
  #   restart: always

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"

  #   networks:
  #     - barev
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   restart: always

volumes:
  postgres:
  ganache:

# networks:
#   barev:
#     driver: bridge
